config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets do
    resources :comments, only: :create
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :tweet, optional: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, foreign_key: "tweet_id", dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, foreign_key: :user_id, dependent: :destroy
  has_many :comments, foreign_key: :user_id, dependent: :destroy
  mount_uploader :avatar, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :move_to_sign_in

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.create(comment_params)
    redirect_to tweet_path(params[:tweet_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id)
  end

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_sign_in, except: :index

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.create(tweet_params)
    redirect_to root_path
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = @tweet.comments.new
    @comments = Comment.where(tweet_id: @tweet.id)
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params) if tweet.user == current_user
    redirect_to tweet_path(params[:id])
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user == current_user
    redirect_to root_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text, :image).merge(user_id: current_user.id)
  end

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
.main__show-comments--content_list
  - if comment.user.avatar.present?
    = image_tag (comment.user.avatar.url), class: 'u-avatar'
  - else
    = image_tag 'avatar.png', class: 'u-avatar'
  .main__show-comments--content_list--text
    .main__show-comments--content_list--text__user-name
      = comment.user.nickname
    .main__show-comments--content_list--text__body
      = comment.text

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyTweet
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: :"https://fonts.googleapis.com/css?family=Kaushan+Script|Gloria+Hallelujah|M+PLUS+1p|Permanent+Marker", rel: :"stylesheet"}/
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :integrity => "sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/", :rel => "stylesheet"}/

  %body
    .header
      = link_to root_path do
        .header-title
          My Tweet
      .header-btn
        - if user_signed_in?
          - if current_user.avatar.present?
            = image_tag (current_user.avatar.url), class: 'u-avatar'
          - else
            = image_tag 'avatar.png', class: 'u-avatar'
          = link_to destroy_user_session_path, method: :delete, class: 'btn-link' do
            .header-btn__box
              Log Out
        -else
          = link_to new_user_session_path, class: 'btn-link' do
            .header-btn__box
              Log In
          = link_to new_user_registration_path, class: 'btn-link' do
            .header-btn__box
              Sign Up

    = yield

    .footer
      .footer-container
        Copyright © 2019 Iwai Inc. All Rights Reserved.

app/views/tweets/_tweet.html.haml
.main__tweet
  .main__tweet-image
    = image_tag (tweet.image.url), class: 'tweet-img'
  .main__tweet-user
    - if tweet.user.avatar.present?
      = image_tag (tweet.user.avatar.url), class: 'u-avatar'
    - else
      = image_tag 'avatar.png', class: 'u-avatar'
    .main__tweet-user_name
      = tweet.user.nickname
  .main__tweet-menu
    = fa_icon 'angle-double-down', class: 'icon'
    .main__tweet-menu__list
      = link_to tweet_path(tweet.id), class: 'btn-link'do
        .main__tweet-menu__list-box
          More Detail
      - if current_user == tweet.user
        = link_to edit_tweet_path(tweet.id), class: 'btn-link'do
          .main__tweet-menu__list-box
            Edit
        = link_to tweet_path(tweet.id), method: :delete, class: 'btn-link' do
          .main__tweet-menu__list-box
            Delete
  .main__tweet-text
    = tweet.text

app/views/tweets/edit.html.haml
.main
  .main__new-form
    = form_for @tweet do |f|
      .main__new-form__top
        = f.text_area :text, class: 'text-form'
      .main__new-form__bottom
        .main__new-form__bottom-image
          = f.file_field :image, class: 'hidden'
          = fa_icon 'camera-retro 5x'
        = f.submit 'Edit Tweet', class: 'main__new-form__bottom-btn'

app/views/tweets/index.html.haml
.main
  = render @tweets
  .pagenate
    = paginate(@tweets)

  = link_to new_tweet_path do
    = fa_icon 'feather 8x'

app/views/tweets/new.html.haml
.main
  .main__new-form
    = form_for @tweet do |f|
      .main__new-form__top
        = f.text_area :text, class: 'text-form'
      .main__new-form__bottom
        = f.label :image, class: 'main__new-form__bottom-image' do
          = f.file_field :image, class: 'hidden'
          = fa_icon 'camera-retro 5x'
        = f.submit 'Send Tweet', class: 'main__new-form__bottom-btn'

app/views/tweets/show.html.haml
.main
  .main__show
    .main__show-image
      = image_tag (@tweet.image.url), class: 'tweet-img'
      .main__show-image--text
        = @tweet.text
    .main__show-bottom
      .main__show-bottom__left
        - if @tweet.user.avatar.present?
          = image_tag (@tweet.user.avatar.url), class: 'u-avatar'
        - else
          = image_tag 'avatar.png', class: 'u-avatar'
        %span
          Tweet User
        .main__show-bottom__left__name
          = @tweet.user.nickname
      - if @tweet.user == current_user
        .main__show-bottom__right
          = link_to tweet_path, method: :delete, class: 'btn-link' do
            .main__show-bottom__right-box
              Delete
          = link_to edit_tweet_path, class: 'btn-link' do
            .main__show-bottom__right-box
              Edit

    .main__show-comments
      .main__show-comments--head
        %h2
          * Comments
        - if user_signed_in?
          = fa_icon 'comment 3x'
      .main__show-comments--content
        - if @comments.present?
          = render @comments
        - else
          .main__show-comments--content_no
            Comment, Please.

.comments-container
  .comments-container__modal
    = fa_icon 'times-circle', class: 'cancel-icon'
    = form_for [@tweet, @comment], method: :post do |f|
      = f.text_area :text, class: 'modal-form'
      =f.submit 'post', class: 'modal-submit'